// Date: 11/24/2016 7:15:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMohawk extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer mohawkbase;
    ModelRenderer mohawk1;
    ModelRenderer mohawk2;
    ModelRenderer mohawk3;
    ModelRenderer mohawk4;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
  
  public ModelMohawk()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      mohawkbase = new ModelRenderer(this, 0, 53);
      mohawkbase.addBox(-1F, -10F, -1F, 2, 2, 2);
      mohawkbase.setRotationPoint(0F, 0F, 0F);
      mohawkbase.setTextureSize(64, 64);
      mohawkbase.mirror = true;
      setRotation(mohawkbase, 0F, 0F, 0F);
      mohawk1 = new ModelRenderer(this, 0, 37);
      mohawk1.addBox(-1F, -13F, -4F, 2, 3, 7);
      mohawk1.setRotationPoint(0F, 0F, 0F);
      mohawk1.setTextureSize(64, 64);
      mohawk1.mirror = true;
      setRotation(mohawk1, 0F, 0F, 0F);
      mohawk2 = new ModelRenderer(this, 19, 40);
      mohawk2.addBox(-1F, -12F, -5F, 2, 3, 4);
      mohawk2.setRotationPoint(0F, 0F, 0F);
      mohawk2.setTextureSize(64, 64);
      mohawk2.mirror = true;
      setRotation(mohawk2, -0.6780208F, 0F, 0F);
      mohawk3 = new ModelRenderer(this, 32, 41);
      mohawk3.addBox(-1F, -8F, -7F, 2, 2, 4);
      mohawk3.setRotationPoint(0F, 0F, 0F);
      mohawk3.setTextureSize(64, 64);
      mohawk3.mirror = true;
      setRotation(mohawk3, -1.412787F, 0F, 0F);
      mohawk4 = new ModelRenderer(this, 45, 42);
      mohawk4.addBox(-1F, -7F, -5F, 2, 1, 4);
      mohawk4.setRotationPoint(0F, 0F, 0F);
      mohawk4.setTextureSize(64, 64);
      mohawk4.mirror = true;
      setRotation(mohawk4, -1.635859F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    mohawkbase.render(f5);
    mohawk1.render(f5);
    mohawk2.render(f5);
    mohawk3.render(f5);
    mohawk4.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
